### ISSUE TITLE
Using with stfalcon/tinymce-bundle

### ISSUE THREAD

**Issue by desirelabs** [tweedegolf/media-bundle#19]
Hello, would you give some pieces of information concerning making it work with stfalcon/tinymce-bundle ?

Thanks

**Comment by garak** [comment]
My advice is to avoid any tinymce-related bundle, just include tinymce via a CDN and configure it via javascript.
The following is my usual config:
```js
    var url = document.URL.indexOf('app_dev.php') > 0 ? '/app_dev.php/admin/api/modal' : '/admin/api/modal';
    var media_callback = tinymce_callback(url);
    tinymce.init({
        selector: "textarea:not(.noTiny)",
        menubar: false,
        plugins: ["link", "code", "paste", "image", "table"],
        file_browser_callback: media_callback,
        paste_as_text: false,
        paste_word_valid_elements: "p,a,b,i,u,em,strong,img,ul,ol,li,table,tr,td,h3,h4",
        content_css: "/css/tinymce.css",
        block_formats: "Paragrafo=p;H3=h3;H4=h4",
        toolbar: "undo redo | bold italic underline | formatselect | link | image | bullist numlist | table | code | pastetext | alignleft aligncenter alignright alignjustify",
        language_url : '/js/tinymce_it.js',
        relative_urls: false,
        setup: function (editor) {
            $('#' + editor.id).removeAttr('required');
        }
    });

```

**Comment by desirelabs** [comment]
Allright, thanks but having issues with require functions. Is there anyway to implement your library without require() ?
Thanks again

**Comment by garak** [comment]
I'm not using `require`

**Comment by desirelabs** [comment]
I assume the bundle requires the use of tweedegolf/media-browser, which requires `require`. But maybe I should post on the other repo for this.

**Comment by garak** [comment]
I copied javascripts from tweedegolf/media-browser and adapted to avoid using require.
Anyway, it's not related to this bundle
