### ISSUE TITLE
Dropping Gaufrette requirement

### ISSUE THREAD

**Issue by garak** [tweedegolf/media-bundle#4]
While I consider Gaufrette a nice library, it's an overkill for most applications.
This bundle requires KnpGaufretteBundle, but it could work without it with some minor tweaks.
If you merge current pending PRs, I can do a new PR about this (it's ready made)

**Comment by marlonbaeten** [comment]
Hi garak. Of course your tweaks to drop the Gaufrette dependancy are welcome! While Gaufrette might be overkill for many applications, it makes switching to different a server architecture a breeze (like using a CDN to serve your images). However, I do not know the exact performance overhead Gaufrette introduces for a local filesystem as storage, therefore a PR is welcome :-)
